- name: Install Qualys Agent on Linux targets
  hosts: all
  gather_facts: true
  vars:
         ActivationID: 05cf38c4-aa26-48be-8334-576dd7bb3cd3
         CustomerID: 415d742a-eef1-e6f6-8109-7b278964acaf
         password: $6$h8lKL7TW$8yYNslYVOd/IsOUzxEisjaGqz1P3sgO3BaxyzFXYteXrQAG3YiGGJmne/T5RIyMg.X9mVMWBCN4v.4zXeMPhE/
         password1: "Welc0mE@123"
  tasks:

    - name: create user
      user:
                name: "{{ item }}"
                state: present
                password: "{{ password1 | password_hash('sha512') }}"
      loop:
                - svc-p-pam-fa-linux
    - name: create sudoers file in centos 6
      copy:
                dest: "/etc/sudoers.d/svc-p-pam-fa-linux"
                src: "svc-p-pam-fa-linux.cos6"
                mode: '0440'
                validate: /usr/sbin/visudo -csf %s
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

    - name: create sudoers file in Centos 7
      copy:
                dest: "/etc/sudoers.d/svc-p-pam-fa-linux"
                src: "svc-p-pam-fa-linux.cos7"
                mode: '0440'
                validate: /usr/sbin/visudo -csf %s
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


    - debug: msg= {{ ansible_distribution }}
    - name: create user
      user:
        name: svc-p-qualys
        state: present
        password: "{{ password }}"
    - name: create sudoers file
      copy:
                dest: "/etc/sudoers.d/svc-p-qualys"
                content: "svc-p-qualys ALL=(ALL)  NOPASSWD: ALL"
                mode: '0440'

    - name: Check if Qualys Cloud Agent is Installed Already
      command: systemctl status qualys-cloud-agent
      register: init_status_result
      ignore_errors: yes

    - name: Create Directory for Downloading Qualys Cloud Agent
      file:
        path: /usr/qualys/
        state: directory
        owner: svc-p-qualys
        group: svc-p-qualys
        mode: 0777
        recurse: no

    - name: Debian Download Latest Version of Qualys Cloud Agent
      get_url:
        url: https://172.28.5.66/pub/QualysCloudAgent_Linux_x64_3.1.0.45.deb
        dest: /usr/qualys/qualys-cloud-agent.x86_64.deb
        mode: 0777
        validate_certs: false
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: RPM Download Latest Version of Qualys Cloud Agent
      get_url:
        url: https://172.28.5.66/pub/QualysCloudAgent_Linux_x64_3.1.0.45.rpm
        dest: /usr/qualys/qualys-cloud-agent.x86_64.rpm
        mode: 0755
        validate_certs: false
      when: ansible_distribution == 'Redhat' or ansible_distribution == 'CentOS'

    - name: Execute the Installation Script on RPM
      command: rpm -ivh qualys-cloud-agent.x86_64.rpm
      args:
        chdir: /usr/qualys/
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

    - name: Execute the Installation Script on Debian
      command: dpkg --install qualys-cloud-agent.x86_64.deb
      args:
        chdir: /usr/qualys
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Execute the Activation Script
      shell: /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId={{ActivationID}} CustomerId={{CustomerID}}
#    - local_action: wait_for host={{ ansible_ssh_host  }} port=22 state=started
